# Generated by Django 6.0 on 2025-12-31 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('niveau', models.CharField(choices=[('college', 'Collège'), ('lycee', 'Lycée')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='eleves/')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classe')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('francais', 'Français'), ('anglais', 'Anglais'), ('hg', 'Histoire/Géo'), ('maths', 'Maths'), ('pc', 'Physique/Chimie'), ('svt', 'SVT'), ('ef', 'Education Française'), ('eps', 'EPS'), ('conduite', 'Conduite')], max_length=20)),
                ('coefficient', models.FloatField(default=1)),
                ('classe', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='core.classe')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_note', models.CharField(choices=[('I1', 'Interrogation 1'), ('I2', 'Interrogation 2'), ('I3', 'Interrogation 3'), ('D1', 'Devoir 1'), ('D2', 'Devoir 2'), ('D3', 'Devoir 3'), ('C', 'Composition')], max_length=2)),
                ('valeur', models.FloatField()),
                ('semestre', models.IntegerField(choices=[(1, 'Semestre 1'), (2, 'Semestre 2')])),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.eleve')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.matiere')),
            ],
        ),
    ]
